### ISSUE TITLE
clumpify hanging

### ISSUE THREAD

**Issue by nick-youngblut** [BioInfoTools/BBMap#15]
It appears that running `clumpify` in an SGE job with no enough memory causes an "Exception in Thread" error, but clumpify doesn't die. The process just hangs and continuously waits for all threads. Here's the full log from one run:

```
java -ea -Xmx60g -Xms60g -cp /ebio/abt3_projects/software/dev/llmgqc/.snakemake/conda/72fe9c49/opt/bbmap-37.78/current/ clump.Clumpify -Xmx60g in=/tmp/global2/nyoungblut/LLMGQC_27982106400/NO08/0/1/R1.fq.gz in2=/tmp/global2/nyoungblut/LLMGQC_27982106400/NO08/0/1/R2.fq.gz out=/tmp/global2/nyoungblut/LLMGQC_27982106400/NO08/0/1/R1_dedup.fq.gz out2=/tmp/global2/nyoungblut/LLMGQC_27982106400/NO08/0/1/R2_dedup.fq.gz overwrite=t usetmpdir=t tmpdir=/tmp/global2/nyoungblut/LLMGQC_27982106400/NO08/0/1/ dedupe=t dupedist=2500 optical=t
Executing clump.Clumpify [-Xmx60g, in=/tmp/global2/nyoungblut/LLMGQC_27982106400/NO08/0/1/R1.fq.gz, in2=/tmp/global2/nyoungblut/LLMGQC_27982106400/NO08/0/1/R2.fq.gz, out=/tmp/global2/nyoungblut/LLMGQC_27982106400/NO08/0/1/R1_dedup.fq.gz, out2=/tmp/global2/nyoungblut/LLMGQC_27982106400/NO08/0/1/R2_dedup.fq.gz, overwrite=t, usetmpdir=t, tmpdir=/tmp/global2/nyoungblut/LLMGQC_27982106400/NO08/0/1/, dedupe=t, dupedist=2500, optical=t]
Version 37.78 [-Xmx60g, in=/tmp/global2/nyoungblut/LLMGQC_27982106400/NO08/0/1/R1.fq.gz, in2=/tmp/global2/nyoungblut/LLMGQC_27982106400/NO08/0/1/R2.fq.gz, out=/tmp/global2/nyoungblut/LLMGQC_27982106400/NO08/0/1/R1_dedup.fq.gz, out2=/tmp/global2/nyoungblut/LLMGQC_27982106400/NO08/0/1/R2_dedup.fq.gz, overwrite=t, usetmpdir=t, tmpdir=/tmp/global2/nyoungblut/LLMGQC_27982106400/NO08/0/1/, dedupe=t, dupedist=2500, optical=t]

Read Estimate:          10080760
Memory Estimate:        7691 MB
Memory Available:       48242 MB
Set groups to 1
Executing clump.KmerSort [in1=/tmp/global2/nyoungblut/LLMGQC_27982106400/NO08/0/1/R1.fq.gz, in2=/tmp/global2/nyoungblut/LLMGQC_27982106400/NO08/0/1/R2.fq.gz, out1=/tmp/global2/nyoungblut/LLMGQC_27982106400/NO08/0/1/R1_dedup.fq.gz, out2=/tmp/global2/nyoungblut/LLMGQC_27982106400/NO08/0/1/R2_dedup.fq.gz, groups=1, ecco=false, rename=false, shortname=f, unpair=false, repair=false, namesort=false, ow=true, dedupe=t]

Making comparator.
Made a comparator with k=31, seed=1, border=1, hashes=4
Starting cris 0.
Fetching reads.
Making fetch threads.
Starting threads.
Waiting for threads.
Exception in thread "Thread-9" Exception in thread "Thread-15" Exception in thread "Thread-12" Exception in thread "Thread-11" java.lang.AssertionError: SRR1761740.1 1 length=100
	at hiseq.FlowcellCoordinate.setFrom(FlowcellCoordinate.java:51)
	at clump.ReadKey.<init>(ReadKey.java:46)
	at clump.ReadKey.<init>(ReadKey.java:33)
	at clump.ReadKey.makeKey(ReadKey.java:23)
	at clump.KmerComparator.hash_inner(KmerComparator.java:79)
	at clump.KmerComparator.hash(KmerComparator.java:70)
	at clump.KmerComparator.hash(KmerComparator.java:66)
	at clump.KmerSort$FetchThread.run(KmerSort.java:815)
Exception in thread "Thread-10" Exception in thread "Thread-13" java.lang.AssertionError: SRR1761740.1201 1201 length=100
	at hiseq.FlowcellCoordinate.setFrom(FlowcellCoordinate.java:51)
	at clump.ReadKey.<init>(ReadKey.java:46)
	at clump.ReadKey.<init>(ReadKey.java:33)
	at clump.ReadKey.makeKey(ReadKey.java:23)
	at clump.KmerComparator.hash_inner(KmerComparator.java:79)
	at clump.KmerComparator.hash(KmerComparator.java:70)
	at clump.KmerComparator.hash(KmerComparator.java:66)
	at clump.KmerSort$FetchThread.run(KmerSort.java:815)
Exception in thread "Thread-16" java.lang.AssertionError: SRR1761740.601 601 length=31
	at hiseq.FlowcellCoordinate.setFrom(FlowcellCoordinate.java:51)
	at clump.ReadKey.<init>(ReadKey.java:46)
	at clump.ReadKey.<init>(ReadKey.java:33)
	at clump.ReadKey.makeKey(ReadKey.java:23)
	at clump.KmerComparator.hash_inner(KmerComparator.java:79)
	at clump.KmerComparator.hash(KmerComparator.java:70)
	at clump.KmerComparator.hash(KmerComparator.java:66)
	at clump.KmerSort$FetchThread.run(KmerSort.java:815)
java.lang.AssertionError: SRR1761740.1001 1001 length=29
	at hiseq.FlowcellCoordinate.setFrom(FlowcellCoordinate.java:51)
	at clump.ReadKey.<init>(ReadKey.java:46)
	at clump.ReadKey.<init>(ReadKey.java:33)
	at clump.ReadKey.makeKey(ReadKey.java:23)
	at clump.KmerComparator.hash_inner(KmerComparator.java:79)
	at clump.KmerComparator.hash(KmerComparator.java:70)
	at clump.KmerComparator.hash(KmerComparator.java:66)
	at clump.KmerSort$FetchThread.run(KmerSort.java:815)
java.lang.AssertionError: SRR1761740.801 801 length=31
	at hiseq.FlowcellCoordinate.setFrom(FlowcellCoordinate.java:51)
	at clump.ReadKey.<init>(ReadKey.java:46)
	at clump.ReadKey.<init>(ReadKey.java:33)
	at clump.ReadKey.makeKey(ReadKey.java:23)
	at clump.KmerComparator.hash_inner(KmerComparator.java:79)
	at clump.KmerComparator.hash(KmerComparator.java:70)
	at clump.KmerComparator.hash(KmerComparator.java:66)
	at clump.KmerSort$FetchThread.run(KmerSort.java:815)
Exception in thread "Thread-14" java.lang.AssertionError: SRR1761740.401 401 length=39
	at hiseq.FlowcellCoordinate.setFrom(FlowcellCoordinate.java:51)
	at clump.ReadKey.<init>(ReadKey.java:46)
	at clump.ReadKey.<init>(ReadKey.java:33)
	at clump.ReadKey.makeKey(ReadKey.java:23)
	at clump.KmerComparator.hash_inner(KmerComparator.java:79)
	at clump.KmerComparator.hash(KmerComparator.java:70)
	at clump.KmerComparator.hash(KmerComparator.java:66)
	at clump.KmerSort$FetchThread.run(KmerSort.java:815)
java.lang.AssertionError: SRR1761740.1401 1401 length=100
	at hiseq.FlowcellCoordinate.setFrom(FlowcellCoordinate.java:51)
	at clump.ReadKey.<init>(ReadKey.java:46)
	at clump.ReadKey.<init>(ReadKey.java:33)
	at clump.ReadKey.makeKey(ReadKey.java:23)
	at clump.KmerComparator.hash_inner(KmerComparator.java:79)
	at clump.KmerComparator.hash(KmerComparator.java:70)
	at clump.KmerComparator.hash(KmerComparator.java:66)
	at clump.KmerSort$FetchThread.run(KmerSort.java:815)
java.lang.AssertionError: SRR1761740.201 201 length=71
	at hiseq.FlowcellCoordinate.setFrom(FlowcellCoordinate.java:51)
	at clump.ReadKey.<init>(ReadKey.java:46)
	at clump.ReadKey.<init>(ReadKey.java:33)
	at clump.ReadKey.makeKey(ReadKey.java:23)
	at clump.KmerComparator.hash_inner(KmerComparator.java:79)
	at clump.KmerComparator.hash(KmerComparator.java:70)
	at clump.KmerComparator.hash(KmerComparator.java:66)
	at clump.KmerSort$FetchThread.run(KmerSort.java:815)
Fetch time: 	0.080 seconds.
Closing input stream.
Combining thread output.
Combine time: 	0.000 seconds.
Exception in thread "main" java.lang.AssertionError: 0, 3200, true
	at clump.KmerSort.fetchReads(KmerSort.java:720)
	at clump.KmerSort.processInner(KmerSort.java:398)
	at clump.KmerSort.process(KmerSort.java:310)
	at clump.KmerSort.main(KmerSort.java:51)
	at clump.Clumpify.process(Clumpify.java:243)
	at clump.Clumpify.main(Clumpify.java:37)
```

**Comment by slhogle** [comment]
Spent like the last hour dealing with nearly the same cryptic error message, and I think it has to do with the parsing of fastq headers for the removal of optical duplicates. 

from the manual
`optical=f       If true, mark or remove optical duplicates only. This means they are Illumina reads within a certain distance on the flowcell.  Normal Illumina names needed. Also for tile-edge and well duplicates.`

I was trying to remove duplicates in an ncbi SRA download that didn't have the original illumina header names/formatting. Once I tried this on raw reads with illumina formatting that I'd gotten directly from the sequencing center the error message went away. 

I didn't really do any other testing so I could be wrong here, but my explanation makes sense since illumina headers contain tiling coordinates. hopefully this helps someone else

**Comment by millerh1** [comment]
I had the same error -- it would be nice if there was a way to use clumpify on SRA reads
